<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="stylecop.json" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="Confluent.Kafka" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include=" StyleCop.Analyzers" />
        <PackageReference Include="Polly" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Enrichers.Environment" />
        <PackageReference Include="Serilog.Enrichers.Process" />
        <PackageReference Include="Serilog.Enrichers.Thread" />
        <PackageReference Include="Serilog.Exceptions" />
        <PackageReference Include="Serilog.Extensions.Hosting" />
        <PackageReference Include="Serilog.Sinks.Elasticsearch" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Serilog.Sinks.OpenSearch" />
    </ItemGroup>

    <ItemGroup>
      <Page Include="stylecop.json" />
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccountManager.Application\AccountManager.Application.csproj" />
    <ProjectReference Include="..\AccountManager.Domain\AccountManager.Domain.csproj" />
    <ProjectReference Include="..\AccountManager.Shared\AccountManager.Shared.csproj" />
  </ItemGroup>

</Project>
